=head1 Name

Linux Training

=head2 Fri 17 Nov 2017

Some notes made during the last course are recorded below.

Installation reboot happened just before coffee break.

Commands (slide 17) finished just before lunch break.

Finished upto slide 27 on day 1.


=head2 rsync

 rsync -uvi index.html scripting.html *jpg xr.sh 10-monitor.conf \
 sco@v0262.nbi.ac.uk:/var/www/nondb/html/customers/training/linux/


=head2 Fri 25 Oct 2019

Kubuntu 18.04.3 doesn't include a 1920x1080 resolution. So we will
need to get the students to C<wget> F<xr.sh> ans source it to set the
resolution. I have also put F<10-monitor.conf> on
http://streptomyces.org.uk/customers/training/linux/. This file will
be put in F</etc/X11/xorg.conf.d/> to make this resolution the default
resolution.

The actual modeline can be determined by

 cvt 1920 1080 60

usermod -G docker,vboxusers,wheel,users sco

=head2 Sat 06 Nov 2021

 syncer () {
 rsync -uvi index.html scripting.html *jpg \
 sco@v0262.nbi.ac.uk:/var/www/nondb/html/customers/training/linux/nov2021/
 }



=cut

